# Generated by Django 3.1.2 on 2020-10-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola_area_title', models.CharField(max_length=50)),
                ('escola_area_description', models.CharField(max_length=5000)),
                ('escola_area_photo1', models.ImageField(upload_to='main_website/images/escola')),
                ('escola_area_photo2', models.ImageField(upload_to='main_website/images/escola')),
                ('escola_area_photo3', models.ImageField(upload_to='main_website/images/escola')),
                ('escola_area_photo4', models.ImageField(upload_to='main_website/images/escola')),
                ('escola_area_photo5', models.ImageField(upload_to='main_website/images/escola')),
                ('escola_area_photo6', models.ImageField(upload_to='main_website/images/escola')),
            ],
        ),
    ]
