# Generated by Django 3.1.2 on 2020-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_visitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('photo1', models.ImageField(upload_to='main_website/images/escola')),
                ('photo2', models.ImageField(upload_to='main_website/images/escola')),
                ('photo3', models.ImageField(upload_to='main_website/images/escola')),
                ('photo4', models.ImageField(upload_to='main_website/images/escola')),
                ('photo5', models.ImageField(upload_to='main_website/images/escola')),
                ('photo6', models.ImageField(upload_to='main_website/images/escola')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RenameField(
            model_name='visitation',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
