# Generated by Django 3.1.2 on 2020-11-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0004_auto_20201101_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
