# Generated by Django 3.1.2 on 2020-11-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0006_auto_20201101_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer',
            new_name='Home',
        ),
    ]
