# Generated by Django 3.1.2 on 2020-11-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0007_auto_20201101_1520'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Footer',
        ),
    ]
