# Generated by Django 3.1.2 on 2020-11-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0008_auto_20201101_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diferentials',
            options={'verbose_name': 'Diferenciais'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Rodape da Pagina'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Escola'},
        ),
        migrations.AlterModelOptions(
            name='visitation',
            options={'verbose_name': 'Visitacao'},
        ),
    ]
