# Generated by Django 3.1.2 on 2020-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0009_auto_20201106_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(),
        ),
    ]
